import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../css/style.scss";
import "../css/home.scss";
import "../css/cources.scss";
import IndexApp from ".";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <IndexApp interClass={inter.className}  children={children}/>
    </html>
  );
}
